# Generated code do not commit.
file(TO_CMAKE_PATH "C:\\flutter" FLUTTER_ROOT)
file(TO_CMAKE_PATH "C:\\KULIAH\\SEMESTER\\SEMESTER 5\\Pemrograman Mobile\\TUGAS\\myocr" PROJECT_DIR)

set(FLUTTER_VERSION "0.1.0" PARENT_SCOPE)
set(FLUTTER_VERSION_MAJOR 0 PARENT_SCOPE)
set(FLUTTER_VERSION_MINOR 1 PARENT_SCOPE)
set(FLUTTER_VERSION_PATCH 0 PARENT_SCOPE)
set(FLUTTER_VERSION_BUILD 0 PARENT_SCOPE)

# Environment variables to pass to tool_backend.sh
list(APPEND FLUTTER_TOOL_ENVIRONMENT
  "FLUTTER_ROOT=C:\\flutter"
  "PROJECT_DIR=C:\\KULIAH\\SEMESTER\\SEMESTER 5\\Pemrograman Mobile\\TUGAS\\myocr"
  "FLUTTER_ROOT=C:\\flutter"
  "FLUTTER_EPHEMERAL_DIR=C:\\KULIAH\\SEMESTER\\SEMESTER 5\\Pemrograman Mobile\\TUGAS\\myocr\\windows\\flutter\\ephemeral"
  "PROJECT_DIR=C:\\KULIAH\\SEMESTER\\SEMESTER 5\\Pemrograman Mobile\\TUGAS\\myocr"
  "FLUTTER_TARGET=C:\\KULIAH\\SEMESTER\\SEMESTER 5\\Pemrograman Mobile\\TUGAS\\myocr\\lib\\main.dart"
  "DART_DEFINES=RkxVVFRFUl9XRUJfQVVUT19ERVRFQ1Q9dHJ1ZQ==,RkxVVFRFUl9XRUJfQ0FOVkFTS0lUX1VSTD1odHRwczovL3d3dy5nc3RhdGljLmNvbS9mbHV0dGVyLWNhbnZhc2tpdC8wNTQ1Zjg3MDVkZjMwMTg3N2Q3ODcxMDdiYWMxYTZlOWZjOWVlMWFkLw=="
  "DART_OBFUSCATION=false"
  "TRACK_WIDGET_CREATION=true"
  "TREE_SHAKE_ICONS=false"
  "PACKAGE_CONFIG=C:\\KULIAH\\SEMESTER\\SEMESTER 5\\Pemrograman Mobile\\TUGAS\\myocr\\.dart_tool\\package_config.json"
)
