name: myocr
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  camera: ^0.10.5+5
  cloud_firestore: ^4.13.3
  firebase_auth: ^4.14.1
  firebase_core: ^2.23.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.2.0+1
  flutter_riverpod: ^2.4.6
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  riverpod_annotation: ^2.3.1
  image_picker: ^1.0.4
  firebase_storage: ^11.5.5
  permission_handler: ^11.0.1
  image: ^4.1.3
  timelines: ^0.1.0
  path_provider: ^2.1.1
  image_cropper: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  riverpod_generator: ^2.3.6
  build_runner: ^2.4.6
  custom_lint: ^0.5.6
  riverpod_lint: ^2.3.4
  freezed: ^2.4.5
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
